### ISSUE TITLE
not able to connect to db

### ISSUE THREAD

**Issue by jamsung** [spring-guides/gs-accessing-data-mysql#11]
Hi,
I am following your example. Except, that my mysql is hosted in a docker.
I have published the mysql port to be accessible outside of docker so that i can run this spring application locally and connect to mysql db hosted in docker. 
I can run this example successfully if i use the root user settings but does not work for spring user. I am getting following error.

java.sql.SQLException: Access denied for user 'springuser'@'172.17.0.1' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[mysql-connector-java-5.1.46.jar:5.1.46]

I can confirm that i have granted all privileges to spring user. inspite of that i am not able to access the db using this user credentials.

do i need to do anything specific to access using spring user?

thanks
jamsung

**Comment by gregturn** [comment]
Have you verified accessing that exact username/password/host/port from the command line?

**Comment by jamsung** [comment]
hi,
yes - when you say command line - from the SQL command line interface inside docker.

thanks - jamsung

**Comment by ocarlsen** [comment]
Hey @jamsung and @gregturn.  I was having the same problem, running MySQL in a container, getting this error:

```
Caused by: java.sql.SQLException: Access denied for user 'springuser'@'172.21.0.1' (using password: YES)
``` 

The reason is that the tutorial says to create the user for 'localhost', which works fine when running MySQL locally.  But when we run MySQL on docker, the Spring app connects via the docker container network.  That's why we get the '172.21.0.1' instead of 'localhost'.

So, to fix for use with MySQL on docker, create the user with '%':
```
create user 'springuser'@'%' identified by 'ThePassword';
grant all on db_example.* to 'springuser'@'%';
```

HTH.

**Comment by dsyer** [comment]
N.B. If you use the `docker-compose.yml` from this project you wouldn't need to do that step.
